add_newline = true

[directory]
truncation_length = 3

[git_branch]
symbol = "ğŸŒ¿ "

[git_status]
conflicted = "âš¡"
ahead = "â¬†ï¸ "
behind = "â¬‡ï¸ "
staged = "âœ“"
modified = "âœ—"
untracked = "?"

[nodejs]
symbol = "â¬¢ "

[python]
symbol = "ğŸ "

[docker]
symbol = "ğŸ³ "

[character]
success_symbol = "[âœ”](green)"
error_symbol = "[âœ–](red)"